# Generated by Django 4.1.8 on 2023-04-17 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
                ('Firstname', models.CharField(max_length=60)),
                ('Lastname', models.CharField(max_length=60)),
                ('Age', models.IntegerField()),
                ('Team', models.CharField(max_length=60)),
                ('Position', models.CharField(max_length=60)),
                ('Height', models.IntegerField()),
                ('Weight', models.IntegerField()),
                ('College', models.CharField(max_length=60)),
            ],
        ),
    ]
