# Generated by Django 4.1.8 on 2023-04-17 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('username', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
                ('Firstname', models.CharField(max_length=60)),
                ('Lastname', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('TeamName', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('TeamManagerUserName', models.CharField(max_length=60)),
                ('TeamManagerEmail', models.CharField(max_length=60)),
                ('TeamManagerPassword', models.CharField(max_length=60)),
                ('TeamManagerFirstname', models.CharField(max_length=60)),
                ('TeamManagerLastname', models.CharField(max_length=60)),
                ('Country', models.CharField(max_length=60)),
                ('GamesWon', models.IntegerField()),
                ('GamesLost', models.IntegerField()),
            ],
        ),
    ]
