# Generated by Django 4.1.8 on 2023-04-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0002_referee_teams'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentOrganizer',
            fields=[
                ('username', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
                ('Firstname', models.CharField(max_length=60)),
                ('Lastname', models.CharField(max_length=60)),
            ],
        ),
    ]
