# Generated by Django 4.1.8 on 2023-04-29 16:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0003_tournamentorganizer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('GameDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('Referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Userapp.referee')),
                ('Team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_team1', to='Userapp.teams')),
                ('Team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_team2', to='Userapp.teams')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CurrentStage', models.IntegerField()),
                ('Name', models.CharField(max_length=60)),
                ('Skill_Level', models.IntegerField()),
                ('TournamentSize', models.IntegerField()),
                ('Organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Userapp.tournamentorganizer')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='AccountBalance',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TournamentStage5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Game1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ts5_games_team1', to='Userapp.games')),
                ('Game10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ts5_games_team10', to='Userapp.games')),
                ('Game11', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ts5_games_team11', to='Userapp.games')),
                ('Game12', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ts5_games_team12', to='Userapp.games')),
                ('Game13', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ts5_games_team13', to='Userapp.games')),
                ('Game14', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ts5_games_team14', to='Userapp.games')),
                ('Game15', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ts5_games_team15', to='Userapp.games')),
                ('Game16', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ts5_games_team16', to='Userapp.games')),
                ('Game2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ts5_games_team2', to='Userapp.games')),
                ('Game3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ts5_games_team3', to='Userapp.games')),
                ('Game4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ts5_games_team4', to='Userapp.games')),
                ('Game5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ts5_games_team5', to='Userapp.games')),
                ('Game6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ts5_games_team6', to='Userapp.games')),
                ('Game7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ts5_games_team7', to='Userapp.games')),
                ('Game8', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ts5_games_team8', to='Userapp.games')),
                ('Game9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ts5_games_team9', to='Userapp.games')),
                ('Tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Userapp.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentStage4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Game1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ts4_games_team1', to='Userapp.games')),
                ('Game2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ts4_games_team2', to='Userapp.games')),
                ('Game3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ts4_games_team3', to='Userapp.games')),
                ('Game4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ts4_games_team4', to='Userapp.games')),
                ('Game5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ts4_games_team5', to='Userapp.games')),
                ('Game6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ts4_games_team6', to='Userapp.games')),
                ('Game7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ts4_games_team7', to='Userapp.games')),
                ('Game8', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ts4_games_team8', to='Userapp.games')),
                ('Tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Userapp.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentStage3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Game1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ts3_games_team1', to='Userapp.games')),
                ('Game2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ts3_games_team2', to='Userapp.games')),
                ('Game3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ts3_games_team3', to='Userapp.games')),
                ('Game4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ts3_games_team4', to='Userapp.games')),
                ('Tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Userapp.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentStage2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Game1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ts2_games_team1', to='Userapp.games')),
                ('Game2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ts2_games_team2', to='Userapp.games')),
                ('Tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Userapp.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentStage1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Game1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ts1_games_team1', to='Userapp.games')),
                ('Game2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ts1_games_team2', to='Userapp.games')),
                ('Tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Userapp.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventType', models.CharField(max_length=60)),
                ('EventStart', models.DateTimeField(default=datetime.datetime(2023, 4, 29, 16, 22, 58, 184886, tzinfo=datetime.timezone.utc))),
                ('EventEnd', models.DateTimeField()),
                ('EventParticipants', models.CharField(max_length=500)),
                ('EventOrganizer', models.CharField(max_length=200)),
                ('Team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Userapp.teams')),
            ],
        ),
    ]
