# Generated by Django 3.2 on 2023-04-30 19:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0004_games_tournament_user_accountbalance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='EventName',
            field=models.CharField(default='TeamEvent', max_length=300),
        ),
        migrations.AlterField(
            model_name='event',
            name='EventStart',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 30, 19, 7, 11, 241165, tzinfo=utc)),
        ),
    ]
