# Generated by Django 3.2 on 2023-04-30 19:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0005_auto_20230430_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='EventStart',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 30, 19, 31, 27, 276419, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='PlayerGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('rebounds', models.IntegerField()),
                ('steals', models.IntegerField()),
                ('blocks', models.IntegerField()),
                ('game_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Userapp.games')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Userapp.user')),
            ],
        ),
    ]
